language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
install:
  - printenv
  - npm install
script:
  - npm test
  - npm run guide:build
  - cp ./.gemini.saucelabs.js ./.gemini.js
  - npm run gemini:test

deploy:
  provider: surge
  project: ./guide/
  on: gemini-test-enable